FROM node:18-alpine

WORKDIR /app

# Build context: ./ui
# → Bu yüzden KOPYALARKEN ui/ yazmıyoruz ❌

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
