services:
  backend:
    container_name: rag-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8008:8008"
    volumes:
      - chroma_data:/app/data/chroma_db
      - ./data/sources:/app/data/sources
      - ./data/cache:/app/data/cache
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8008
    restart: unless-stopped
    mem_limit: 4G

  ui:
    container_name: rag-ui
    build:
      context: ./ui
      dockerfile: ../Dockerfile.ui
    ports:
      - "5177:5177"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8008
    restart: unless-stopped

volumes:
  chroma_data:
